services:
  nuxt:
    image: node:latest
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    networks:
        - sail

